<?php
/**
 * TL_ROOT/system/modules/catalogajaxratingfield/languages/de/tl_catalog_fields.php 
 * 
 * Contao extension: cataloggooglemapsfield 0.1 beta1 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2011 Nikolas Runde
 * License   : LGPL 
 * Author    : Nikolas Runde, http://www.nrmedia.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_catalog_fields']['typeOptions']['googlemapsfield'] = "Kartenfeld";


$GLOBALS['TL_LANG']['tl_catalog_fields']['googlemaps_latfield']['0'] = "Breitengrad";
$GLOBALS['TL_LANG']['tl_catalog_fields']['googlemaps_latfield']['1'] = "Geben Sie hier das Feld f&uuml;r den Breitengrad an";

$GLOBALS['TL_LANG']['tl_catalog_fields']['googlemaps_lonfield']['0'] = "Längengrad";
$GLOBALS['TL_LANG']['tl_catalog_fields']['googlemaps_lonfield']['1'] = "Geben Sie hier das Feld f&uuml;r den Längengrad an";

$GLOBALS['TL_LANG']['tl_catalog_fields']['googlemaps_zoomfield']['0'] = "Zoom";
$GLOBALS['TL_LANG']['tl_catalog_fields']['googlemaps_zoomfield']['1'] = "Geben Sie hier das Feld f&uuml;r den Zoom an";
?>
